import turtle
ctr = turtle.Turtle()
ctr.pensize(2.3)
ctr.speed(10)
ctr.goto(0,0)
for i in range(50): 
    ctr.pencolor("magenta")
    ctr.right(20)
    ctr.forward(60)
    ctr.pencolor("purple")
    ctr.left(70)
    ctr.forward(100)
    ctr.pencolor("green")
    ctr.left(100)
    ctr.forward(120)
    ctr.pencolor("black")
    ctr.right(120)
    ctr.forward(160)
    ctr.pencolor("red")
    ctr.left(170)
    ctr.forward(180)
    ctr.pencolor("orange")
    ctr.left(90)
    ctr.forward(90)
ctr.hideturtle()
ctr.done()
